const studentFilterList = [
  'name.firstName',
  'name.lastName',
  'email',
  'gender',
  'dateOfBirth',
  'contactInfo',
  'id',
  'academicSemester',
  'academicFaculty',
  'academicDepartment',
  'bloodGroup',
  'guardian.fatherName',
  'guardian.fatherOccupation',
  'guardian.fatherContactNo',
  'guardian.motherName',
  'guardian.motherOccupation',
  'guardian.motherContactNo',
  'guardian.guardianName',
  'guardian.guardianOccupation',
  'guardian.guardianContactNo',
  'guardian.guardianRelation',
  'presentAddress',
  'permanentAddress',
  'profileImage',
  'createdAt',
  'updatedAt',
];

export { studentFilterList };
